project_id = "pahfisskacgnxiphyrrh"

[functions.robots]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.seo-routes]
verify_jwt = false

[functions.send-contact-notification]
verify_jwt = false

[functions.tmp-upload-media]
verify_jwt = false
