// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { normalizeAssetUrls } from '@/lib/assetUrl';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;


function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return async (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    const response = await fetch(input, { ...init, headers });

    // Content saved by the dashboard can contain Lovable asset paths. Vite can
    // rewrite imported *.asset.json files, but it cannot rewrite values fetched
    // later from Supabase. Normalize those responses so media also works when
    // the built site is hosted on Vercel, Netlify, or another static host.
    if (response.headers.get('content-type')?.includes('application/json')) {
      const text = await response.clone().text();
      if (text.includes('"/__l5e/')) {
        try {
          const normalized = JSON.stringify(normalizeAssetUrls(JSON.parse(text)));
          const responseHeaders = new Headers(response.headers);
          responseHeaders.delete('content-length');
          return new Response(normalized, {
            status: response.status,
            statusText: response.statusText,
            headers: responseHeaders,
          });
        } catch {
          // Preserve the original response if a non-standard JSON body is used.
        }
      }
    }

    return response;
  };
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: {
    fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
  },
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
